### ISSUE TITLE
func List() 

### ISSUE THREAD

**Issue by wanderself** [olebedev/config#13]
1st, thx 4 giving the great go lib!
and i have a question in my dev programs:
func List()  return a []interface{} for us ,
but how can i use the var(type []interface) as type []string?
hope ur responed

**Comment by olebedev** [comment]
Hi @wanderself, the lib doesn't bring`.StringList` method. It seems only one possible scenario is to create new `[]string` and iterate over `[]interface{}` converting item to string and pushing into new list.

**Comment by wanderself** [comment]
Found a easy way:
1st. use the Map() method to get a map[string]interface{}
2nd. import "github.com/spf13/cast" and use cast.ToStringSlice(map["key"]) to get a []string{}
