### ISSUE TITLE
Set() does not work

### ISSUE THREAD

**Issue by theduke** [olebedev/config#3]
.Set() does not seem to actually work.

```go
cfg.Set("testVal", "test")
x := cfg.UString("testVal", "")
// X is ""!
```

**Comment by olebedev** [comment]
Actually, `.Set()` works only with existing values. 
Could you provide initial config string?

**Comment by theduke** [comment]
Could you implement the option to .Set() new values?

Otherwise I could look into it and do a PR.

Sadly I can't provide a default value in the yaml/json.

**Comment by theduke** [comment]
Great work, thanks a lot!

**Comment by olebedev** [comment]
:+1:
